### ISSUE TITLE
Missing currency in PaymentsListItem

### ISSUE THREAD

**Issue by davide-bontempelli-zupit** [fattureincloud/fattureincloud-python-sdk#49]
Just wondering if it's correct that [ReceivedDocumentPaymentsListItem](https://github.com/fattureincloud/fattureincloud-python-sdk/blob/b02a37c925d79f5944ef6ab989fa5e16d548cd87/docs/ReceivedDocumentPaymentsListItem.md) and [IssuedDocumentPaymentsListItem](https://github.com/fattureincloud/fattureincloud-python-sdk/blob/b02a37c925d79f5944ef6ab989fa5e16d548cd87/docs/IssuedDocumentPaymentsListItem.md)
have the amount field but no currency. The payment's currency it's always the document's currency?

**Comment by emajo** [comment]
Hi @davide-bontempelli-zupit, yes the document currency is global for every item, sorry for the late answer, I suggest to write on [our community](https://github.com/fattureincloud/api/discussions) to receive faster answer from our team.

Thanks,
Emanuele.
