### ISSUE TITLE
country Client proprerties

### ISSUE THREAD

**Issue by giordy84** [fattureincloud/fattureincloud-python-sdk#52]
Hi,
when creating a client I don't understand what data I have to insert in the "country" value.
The documentation says a string type field but by entering "IT" or "Italy" the data is not accepted.

I suggest you modify the field with an ISO type code so that you can enter a unique data and that it is accepted.

I await your reply

**Comment by emajo** [comment]
Hi @giordy84 we have also a `country_iso` field you can use instead of `country`, in the `country` field we accept only country names in italian, if you have other questions not specific for this sdk I suggest to create a new discussion [here](https://github.com/fattureincloud/api/discussions).
