### ISSUE TITLE
2.0.12 moves symbols around

### ISSUE THREAD

**Issue by jpaniagualaconich** [fattureincloud/fattureincloud-python-sdk#55]
**Describe the bug**
Some symbols are in different places now. If intended, this breaks semantic versioning.

**Env info**
Python version: `3.10.7`
Python SDK version:  `2.0.12`

**To Reproduce**

```python
>>> from fattureincloud_python_sdk.model.create_issued_document_response import CreateIssuedDocumentResponse
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'fattureincloud_python_sdk.model'
```

It's OK in previous version `2.0.11`

**Expected behavior**
No need to change imports between `2.0.11` and `2.0.12`

**Comment by emajo** [comment]
Hi @jpaniagualaconich, in the last version of the python sdk we made some minor changes for performance reasons and to fit better the python code standards, we will put this changes in the changelog as soon as possible.
To fix the imports it's enough to change fattureincloud_python_sdk.model to fattureincloud_python_sdk.models
We are sorry for the undocumented changes, we will surely make a migration guide.

Thanks,
Emanuele.

**Comment by jpaniagualaconich** [comment]
Thanks for the prompt response, @emajo .
Sure, the work-around is simple.

Feel free to close this issue at your discretion.

**Comment by emajo** [comment]
We added the changes to our [changelog](https://github.com/fattureincloud/fattureincloud-python-sdk/blob/master/CHANGELOG.md).

Thanks again,
Emanuele.
