### ISSUE TITLE
IssuedDocument.locked is no longer accessible

### ISSUE THREAD

**Issue by jpaniagualaconich** [fattureincloud/fattureincloud-python-sdk#64]
**Describe the bug**
`IssuedDocument.locked` is no longer accessible. The `locked` attribute is still present [in the documentation](https://developers.fattureincloud.it/api-reference/#get-/c/-company_id-/issued_documents/-document_id-).

**Env info**
- python version: 3.11.2
- fattureincloud-python-sdk in {'2.0.12', '2.0.13', '2.0.14', '2.0.15'} (it was working fine until '2.0.11')

**To Reproduce**

```python
from fattureincloud_python_sdk import ApiClient, ApiException, Configuration
from fattureincloud_python_sdk.api.issued_documents_api import IssuedDocumentsApi

company_id = 111222
access_token = "my-secret-token"
invoice_number = 666
invoice_numeration = "-NUMERATION"

config = Configuration()
config.access_token = access_token
api_client = ApiClient(configuration=config)
issued_documents_api = IssuedDocumentsApi(api_client)

request_kwargs = {
    "fieldset": "detailed",
    "q": f"number='{invoice_number}' AND numeration='{invoice_numeration}'",
}

response = issued_documents_api.list_issued_documents(company_id, "invoice", **request_kwargs)

doc_list = response.data
doc_list[0].locked
```

This results in:
```txt
AttributeError: 'IssuedDocument' object has no attribute 'locked'
```

Trying `.to_dict()['locked']` or `.dict()['locked']` does not work either.

**Expected behavior**
Getting a `True` or a `False`

**Comment by emajo** [comment]
Hi @jpaniagualaconich we removed the `locked` field a while ago, if you look the schemas in the documentation you will see it's not there anymore, but we forgot to remove it also from the examples. Can I ask what are you using the locked field for?

Thanks,
Emanuele.

**Comment by jpaniagualaconich** [comment]
Hi @emajo

We were using it to determine if we could modify an issued document freely or we should only make changes to `payments_list` .

**Comment by emajo** [comment]
Actually I checked and the `locked` field was never documented, so never added to the Issued Document class, I will explain why you are able to use it in the other issue you opened, we will add this field in the next release.

Thanks,
Emanuele.

**Comment by vad** [comment]
did you consider adding a `py.typed` file to the package root, in order to mark the package as typed? Type checkers would make upgrades safer.

**Comment by emajo** [comment]
Hi @vad , thanks for the suggestion, we could definitely look into it in the future, but it is not an easy task as we use the [Openapi Generator](https://github.com/OpenAPITools/openapi-generator) to generate our SDKs and adding something like that needs work on the generator itself.

**Comment by vad** [comment]
@emajo I'm not sure I understand: do you mean you cannot easily add the file, or add type hints?

**Comment by emajo** [comment]
@vad it's about adding the file generation and template and waiting for the release, luckily I just checked and it's already included in the next Openapi generator release (scheduled for the end of month), this is the [PR](https://github.com/OpenAPITools/openapi-generator/pull/15804/files#diff-01f9ea9d84c3690b844a5f5775d903aa8762658b538c340bf7534ce2d6ce9e4e), if everything works as expected it will also be included in our next sdk version.

**Comment by vad** [comment]
@emajo any news?

**Comment by emajo** [comment]
Hi @vad, we just released a new sdk version containing the `locked` field for both the Issued Document and Received Document resource types.

Thanks,
Emanuele.
