### ISSUE TITLE
Upgrade to pydantic v2

### ISSUE THREAD

**Issue by DanieleIsoni** [fattureincloud/fattureincloud-python-sdk#65]
**Is your feature request related to a problem? Please describe.**
We would like to use in our project pydantic v2 but since we depend on fattureincloud-python-sdk we cannot use it

**Describe the solution you'd like**
Upgrade pydantic to v2 in fattureincloud-python-sdk

**Comment by emajo** [comment]
Hi @DanieleIsoni, as explained [here](https://github.com/fattureincloud/fattureincloud-python-sdk/issues/60#issuecomment-1631108748) we don't know when we will start using pydantic v2 as we use Openapi generator to generate our SDKs.

Thanks,
Emanuele.
